import type { Metadata } from 'next'
import { Cormorant_Garamond, Inter, Megrim } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import Navbar from '@/components/Navbar'
import { cn } from '@/lib/utils'
import SmoothScrolling from '@/components/SmoothScrolling'
import Footer from '@/components/templates/Footer'

const inter = Inter({ subsets: ['latin'] })

const garamond = Cormorant_Garamond({
	subsets: ['latin'],
	display: 'swap',
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-garamond'
})

const megrim = Megrim({
	subsets: ['latin'],
	weight: '400',
	display: 'swap',
	style: 'normal',
	variable: '--font-megrim'
})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={`${megrim.variable} ${garamond.variable} ${inter.className}`} suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased max-w-full transition-all duration-300 ease-in-out dark:bg-dot-gray-400/[0.1] bg-dot-black/[0.1]'
				)}
			>
				<ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
					<Navbar />
					<main className=''>
						<SmoothScrolling>{children}</SmoothScrolling>
					</main>
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
